# Generated by Django 3.2.4 on 2021-07-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(max_length=10)),
                ('class_type', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('nuetralized', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
